# Generated by Django 4.2.13 on 2024-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbschallenge", "0002_company_pricedata_dividend"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuryYield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("coupon", models.FloatField()),
                ("price", models.FloatField()),
                ("yield_percent", models.FloatField()),
                ("one_month_change", models.IntegerField()),
                ("one_year_change", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
