# Generated by Django 4.2.13 on 2024-05-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbschallenge", "0004_reit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
