# Generated by Django 4.2.13 on 2024-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbschallenge", "0005_userprofile_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inflation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("inflation_rate", models.FloatField()),
                ("annual_change", models.FloatField()),
            ],
        ),
    ]
